POST http://localhost:3001/starchart
Content-Type: application/json
 
{
        "name": "Jaclene",
        "year": 1990,
        "month": 8,
        "day": 20,
        "hour": 15,
        "minute": 57,
        "longitude": 12.4963655,
        "latitude": 41.9027835,
        "city": "New York",
        "timezone": "Europe/Rome",
        "language": "EN"

}