PUT http://localhost:3001/starchart/edit/628d2431db03a616b047f2e7
Content-Type: application/json

 
{ "properties": {
        "name": "Jaclene",
        "year": 1990,
        "month": 8,
        "day": 20,
        "hour": 15,
        "minute": 57,
        "longitude": 12.4963655,
        "latitude": 41.9027835,
        "city": "New York",
        "timezone": "Europe/Rome",
        "language": "EN"
}
}
